import React from 'react';
import { motion } from 'framer-motion';
import { Quote, Users, Leaf, Lightbulb, Award, Target, Eye, Trophy, Globe, Heart } from 'lucide-react';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import bothCoFounders from '@/assets/both.jpg';
import awardImage from '@/assets/award.jpg';

const About = () => {
  const values = [
    {
      icon: Leaf,
      title: 'Sustainability',
      description: 'Environmental responsibility is at the core of everything we do, from sourcing to production.'
    },
    {
      icon: Lightbulb,
      title: 'Innovation',
      description: 'We continuously push boundaries to develop cutting-edge solutions for a sustainable future.'
    },
    {
      icon: Award,
      title: 'Quality',
      description: 'We maintain the highest standards in our products, ensuring they meet and exceed expectations.'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-green-50">
      <Navigation />
      
      {/* Hero Section */}
      <section className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
              About <span className="text-blue-600">BioLabMate</span>
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Pioneering sustainable solutions through seaweed-based bioplastics for a greener future
            </p>
          </motion.div>
        </div>
      </section>

      {/* Co-Founder's Message */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="relative"
          >
            <div className="bg-gradient-to-br from-blue-600 to-blue-700 rounded-3xl p-8 md:p-12 text-white shadow-2xl">
              <div className="flex items-start gap-4 mb-6">
                <Quote className="w-8 h-8 text-blue-200 flex-shrink-0 mt-1" />
                <h2 className="text-3xl md:text-4xl font-bold">Co-Founder's Message</h2>
              </div>
              <blockquote className="text-lg md:text-xl leading-relaxed italic">
                "We are trying to make a seaweed bioplastic that stands out as a promising alternative. They are renewable, biodegradable, and have less environmental impact than any conventional plastic we use. With a competent team and strong support from the scientific community, we are determined to eradicate petroleum-based plastics from research labs. We are fully committed to this cause and invite you to join us in building eco-sustainable products. Let's save our planet from harmful material and create a greener future..."
              </blockquote>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Our Story */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-white/50">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">Our Story</h2>
            <div className="w-24 h-1 bg-gradient-to-r from-blue-600 to-green-600 mx-auto rounded-full"></div>
          </motion.div>

          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              viewport={{ once: true }}
              className="space-y-6"
            >
              <p className="text-lg text-gray-700 leading-relaxed">
                My co-founder and I have worked on this transformative idea for the last two years. We are both researchers and worked in the research lab for a long time. Our journey began when we noticed the amount of plastic waste generated by research labs.
              </p>
              <p className="text-lg text-gray-700 leading-relaxed">
                We started looking for alternative or biomaterial-based lab plastic products, but unfortunately, we couldn't find any. This led us to seek out other labs facing similar issues, gradually turning our search into a dedicated mission to reduce plastic waste in research labs.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="relative overflow-hidden rounded-2xl shadow-2xl">
                <img
                  src={bothCoFounders}
                  alt="Co-founders working together"
                  className="w-full h-auto object-cover hover:scale-105 transition-transform duration-500"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent"></div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Blue Economy */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <div className="flex items-center justify-center gap-3 mb-6">
              <Globe className="w-8 h-8 text-blue-600" />
              <h2 className="text-4xl md:text-5xl font-bold text-gray-900">Blue Economy</h2>
            </div>
            <div className="w-24 h-1 bg-gradient-to-r from-blue-600 to-green-600 mx-auto rounded-full"></div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            viewport={{ once: true }}
            className="bg-gradient-to-br from-blue-50 to-green-50 rounded-3xl p-8 md:p-12 shadow-xl border border-blue-100"
          >
            <div className="grid md:grid-cols-2 gap-8">
              <div className="space-y-6">
                <p className="text-lg text-gray-700 leading-relaxed">
                  With a coastline stretching 29,000 kilometres, Newfoundland is rich in seaweed, abundantly available along many parts of its shores. Newfoundland holds immense potential for ocean-based derived products. We believe it's an opportunity to utilize readily available raw materials around us to create such products.
                </p>
                <p className="text-lg text-gray-700 leading-relaxed">
                  The global commercial seaweed market is projected to grow from $15.01 billion in 2021 to $24.92 billion in 2028 at a CAGR of 7.51%.
                </p>
              </div>
              <div className="space-y-6">
                <p className="text-lg text-gray-700 leading-relaxed">
                  The potential of bioplastics is vast, evident by the market's impressive Compound Annual Growth Rate (CAGR) of 17.56%, projected to transform it into a thriving $30 billion industry.
                </p>
                <p className="text-lg text-gray-700 leading-relaxed">
                  Particularly remarkable is the untapped opportunity within the Atlantic provinces, which possess abundant resources ripe for bioplastic innovation.
                </p>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Our Values */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-white/50">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">Our Values</h2>
            <div className="w-24 h-1 bg-gradient-to-r from-blue-600 to-green-600 mx-auto rounded-full"></div>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            {values.map((value, index) => (
              <motion.div
                key={value.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: index * 0.2 }}
                viewport={{ once: true }}
                className="group"
              >
                <div className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 border border-gray-100 hover:border-blue-200 h-full">
                  <div className="flex items-center justify-center w-16 h-16 bg-gradient-to-br from-blue-600 to-green-600 rounded-2xl mb-6 group-hover:scale-110 transition-transform duration-300">
                    <value.icon className="w-8 h-8 text-white" />
                  </div>
                  <h3 className="text-2xl font-bold text-gray-900 mb-4">{value.title}</h3>
                  <p className="text-gray-600 leading-relaxed">{value.description}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Mission & Vision */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">Mission & Vision</h2>
            <div className="w-24 h-1 bg-gradient-to-r from-blue-600 to-green-600 mx-auto rounded-full"></div>
          </motion.div>

          <div className="grid lg:grid-cols-2 gap-8">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              viewport={{ once: true }}
              className="bg-gradient-to-br from-blue-600 to-blue-700 rounded-2xl p-8 text-white shadow-xl"
            >
              <div className="flex items-center gap-3 mb-6">
                <Target className="w-8 h-8 text-blue-200" />
                <h3 className="text-2xl font-bold">Our Mission</h3>
              </div>
              <p className="text-lg leading-relaxed">
                "To revolutionize the materials industry by developing innovative, biodegradable solutions derived from sustainable seaweed sources. We are committed to reducing environmental impact while providing superior alternatives to traditional plastics and laboratory materials."
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              viewport={{ once: true }}
              className="bg-gradient-to-br from-green-600 to-green-700 rounded-2xl p-8 text-white shadow-xl"
            >
              <div className="flex items-center gap-3 mb-6">
                <Eye className="w-8 h-8 text-green-200" />
                <h3 className="text-2xl font-bold">Our Vision</h3>
              </div>
              <p className="text-lg leading-relaxed">
                "To create a world where sustainable materials are the standard, not the exception. We envision laboratories and industries worldwide adopting our eco-friendly solutions, contributing to a cleaner, healthier planet for future generations."
              </p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Achievements */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-white/50">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="mb-12"
          >
            <div className="flex items-center justify-center gap-3 mb-6">
              <Trophy className="w-8 h-8 text-yellow-600" />
              <h2 className="text-4xl md:text-5xl font-bold text-gray-900">Our Achievements</h2>
            </div>
            <div className="w-24 h-1 bg-gradient-to-r from-blue-600 to-green-600 mx-auto rounded-full"></div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            viewport={{ once: true }}
            className="space-y-8"
          >
            <div className="relative overflow-hidden rounded-2xl shadow-2xl max-w-md mx-auto">
              <img
                src={awardImage}
                alt="econext CleanTech Innovation Award"
                className="w-full h-auto object-cover hover:scale-105 transition-transform duration-500"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent"></div>
            </div>
            
            <div className="bg-gradient-to-br from-yellow-50 to-orange-50 rounded-2xl p-8 shadow-lg border border-yellow-200">
              <p className="text-lg text-gray-700 leading-relaxed">
                Proud recipient of the <strong>econext CleanTech Innovation Award (2024)</strong>, recognizing our efforts in accelerating clean growth and sustainable innovation in Newfoundland and Labrador.
              </p>
            </div>
          </motion.div>
        </div>
      </section>



      <Footer />
    </div>
  );
};

export default About;

// import React from 'react';
// import { motion } from 'framer-motion';
// import { Quote, Users, Leaf, Lightbulb, Award, Target, Eye, Trophy, Globe, Heart } from 'lucide-react';
// import Navigation from '@/components/Navigation';
// import Footer from '@/components/Footer';
// import bothCoFounders from '@/assets/both.jpg';
// import awardImage from '@/assets/award.jpg';

// // Try importing only the circular carousel first
// import CircularJourneyCarousel from '../components/CircularJourneyCarousel';

// const About = () => {
//   const values = [
//     {
//       icon: Leaf,
//       title: 'Sustainability',
//       description: 'Environmental responsibility is at the core of everything we do, from sourcing to production.'
//     },
//     {
//       icon: Lightbulb,
//       title: 'Innovation',
//       description: 'We continuously push boundaries to develop cutting-edge solutions for a sustainable future.'
//     },
//     {
//       icon: Award,
//       title: 'Quality',
//       description: 'We maintain the highest standards in our products, ensuring they meet and exceed expectations.'
//     }
//   ];

//   return (
//     <>
//       <Navigation />
//       <div className="min-h-screen">
//         {/* Simple test section */}
//         <section className="py-20 bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-900">
//           <div className="max-w-7xl mx-auto px-4 text-center">
//             <h1 className="text-5xl md:text-7xl font-bold text-white mb-6">
//               Our <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-600">Journey</span>
//             </h1>
//             <p className="text-xl text-gray-300 max-w-3xl mx-auto mb-12">
//               Discover the milestones that have shaped BioLabMate's path from innovative startup to industry leader.
//             </p>
//           </div>
//         </section>

//         {/* Circular Journey Carousel */}
//         <section className="relative">
//           <CircularJourneyCarousel />
//         </section>

//         {/* Your original about content */}
//         <section className="py-20 bg-slate-900">
//           <div className="max-w-7xl mx-auto px-4">
//             <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
//               <div className="text-white space-y-6">
//                 <Quote className="text-blue-400 mb-4" size={32} />
//                 <p className="text-lg leading-relaxed italic text-gray-300">
//                   "We are trying to make a seaweed bioplastic that stands out as a promising alternative. They are renewable, biodegradable, and have less environmental impact than any conventional plastic we use. With a competent team and strong support from the scientific community, we are determined to eradicate petroleum-based plastics from research labs."
//                 </p>
//                 <p className="text-lg leading-relaxed text-gray-300">
//                   My co-founder and I have worked on this transformative idea for the last two years. We are both researchers and worked in the research lab for a long time. Our journey began when we noticed the amount of plastic waste generated by research labs.
//                 </p>
//               </div>
//               <div className="relative">
//                 <img 
//                   src={bothCoFounders} 
//                   alt="BioLabMate Co-founders" 
//                   className="rounded-2xl shadow-2xl w-full"
//                 />
//               </div>
//             </div>
//           </div>
//         </section>

//         {/* Values section */}
//         <section className="py-20 bg-slate-800">
//           <div className="max-w-7xl mx-auto px-4">
//             <h2 className="text-4xl font-bold text-white text-center mb-16">Our Values</h2>
//             <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
//               {values.map((value, index) => (
//                 <div key={index} className="bg-slate-900/60 backdrop-blur-md rounded-xl p-6 border border-slate-700/30 text-center">
//                   <value.icon className="text-blue-400 mb-4 mx-auto" size={48} />
//                   <h3 className="text-xl font-bold text-white mb-3">{value.title}</h3>
//                   <p className="text-gray-300">{value.description}</p>
//                 </div>
//               ))}
//             </div>
//           </div>
//         </section>
//       </div>
//       <Footer />
//     </>
//   );
// };

// export default About;